services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      API_ENDPOINT: ${API_ENDPOINT}
      TOKEN_SECRET: ${TOKEN_SECRET}
    command: npm run dev
